# TASK 5

In [1]:
# Implement matrix exponentiation for a square matrix using numpy.

In [2]:
import numpy as np

In [3]:
def exponentiaon_of_matrix(given_matrix, power):
    if power == 0:
        return np.eye(given_matrix.shape[0])
    
    if power == 1:
        return given_matrix
    
    result_matrix = np.eye(given_matrix.shape[0])
    
    base_matrix = given_matrix.copy()
    
    while power > 0:
        if power % 2 == 1:
            result_matrix = np.dot(result_matrix, base_matrix)
            
        base_matrix = np.dot(base_matrix, base_matrix)
        power = power // 2
        
    return result_matrix

In [4]:
size = int(input("Enter size for the square matrix: "))
matrix_values = []

print(f"Enter the values for {size}x{size} matrix: ")

for i in range(size):
    row = []
    
    for j in range(size):
        value = float(input(f"Enter value for position ({i+1}, {j+1}): "))
        row.append(value)
        
    matrix_values.append(row)

given_matrix = np.array(matrix_values)
power = int(input("Enter the power for exponentiation: "))

result_matrix = exponentiaon_of_matrix(given_matrix, power)

print(f"\n Matrix with exponentiation {power} is: ")
print(result_matrix)

Enter size for the square matrix: 3
Enter the values for 3x3 matrix: 
Enter value for position (1, 1): 1
Enter value for position (1, 2): 2
Enter value for position (1, 3): 3
Enter value for position (2, 1): 4
Enter value for position (2, 2): 5
Enter value for position (2, 3): 6
Enter value for position (3, 1): 7
Enter value for position (3, 2): 8
Enter value for position (3, 3): 9
Enter the power for exponentiation: 2

 Matrix with exponentiation 2 is: 
[[ 30.  36.  42.]
 [ 66.  81.  96.]
 [102. 126. 150.]]
